name: Lint, build, test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        # TODO: change to docker image from marinade registry when available
        image: docker.io/ochaloup/solana-test-validator:1.14.18-2
        options: --user root
    timeout-minutes: 15

    strategy:
      fail-fast: true
      matrix:
        node-version: [16]

    steps:
      - name: Link AVM, solana .config, check versions
        run: |
          ln -s /root/.avm $HOME/
          mkdir -p $HOME/.config
          ln -s /root/.config/solana $HOME/.config/
          avm use 0.28.0
          anchor --version
          solana --version


      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Lint, build and test
        timeout-minutes: 5
        run: |
          pnpm install
          pnpm lint
          pnpm build
          pnpm test
        env:
          CI: true
